# Generated by Django 5.0.2 on 2024-02-27 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.CharField(max_length=256)),
                ('patientEmail', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=256)),
                ('service', models.CharField(max_length=156)),
                ('paymentType', models.CharField(max_length=156)),
                ('costOfTreatment', models.FloatField()),
                ('chardOrChackNo', models.CharField(max_length=256)),
                ('createdAtt', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patients')),
            ],
        ),
    ]
