# Generated by Django 4.2.18 on 2025-01-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctors', '0001_initial'),
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notise', models.TextField()),
                ('readStatus', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.CharField(blank=True, max_length=256, null=True)),
                ('patientEmail', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=256)),
                ('service', models.CharField(max_length=156)),
                ('paymentType', models.CharField(max_length=156)),
                ('costOfTreatment', models.FloatField()),
                ('chardOrChackNo', models.CharField(blank=True, max_length=256, null=True)),
                ('createdAtt', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('readStatus', models.BooleanField(default=False)),
                ('creatAt', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appoinments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=156)),
                ('appoinmentDate', models.DateField()),
                ('timeSlot', models.CharField(max_length=20)),
                ('problems', models.TextField()),
                ('tokenNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('reject', models.BooleanField(default=False)),
                ('approveStatus', models.BooleanField(default=False)),
                ('createdAtt', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patients')),
            ],
        ),
    ]
