# Generated by Django 5.0.2 on 2024-02-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UtilsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='patientId',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
