# Generated by Django 5.0.2 on 2024-02-28 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
        ('Patients', '0001_initial'),
        ('UtilsApp', '0002_alter_payment_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='chardOrChackNo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Appoinments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=156)),
                ('appoinmentDate', models.DateField()),
                ('timeSlot', models.CharField(max_length=20)),
                ('problems', models.TextField()),
                ('tokenNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('approveStatus', models.CharField(blank=True, default='Pending', max_length=20, null=True)),
                ('createdAtt', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patients')),
            ],
        ),
    ]
