# Generated by Django 5.0.2 on 2024-03-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UtilsApp', '0003_alter_payment_chardorchackno_appoinments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notise', models.TextField()),
                ('readStatus', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
