# Generated by Django 5.0.2 on 2024-03-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UtilsApp', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinments',
            name='reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appoinments',
            name='approveStatus',
            field=models.BooleanField(default=False),
        ),
    ]
