# Generated by Django 4.2.9 on 2024-02-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='patients_Id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
