# Generated by Django 4.2.10 on 2024-02-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddPatients',
            new_name='Patients',
        ),
    ]
