# Generated by Django 4.2.10 on 2024-02-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_rename_addpatients_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='patients_pic',
        ),
    ]
