# Generated by Django 5.0.2 on 2024-03-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_patients_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='user',
        ),
    ]
