# Generated by Django 5.0.2 on 2024-02-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0003_remove_patients_patients_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='patients_pic',
            field=models.ImageField(default=1, upload_to='patients'),
            preserve_default=False,
        ),
    ]
