# Generated by Django 4.2.9 on 2024-02-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0003_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
