# Generated by Django 4.2.10 on 2024-03-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(max_length=256)),
                ('doctorId', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('speacialization', models.CharField(max_length=256)),
                ('experience', models.CharField(max_length=256)),
                ('age', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('doctor_details', models.TextField()),
                ('doctor_pic', models.ImageField(upload_to='doctor_img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
